### ISSUE TITLE
Plug-in to NEMO the particle tracking model (PARCELS,Livljobs7)

### ISSUE THREAD

**Issue by vleguenn** [ocgabs/Caribbean#3]
Livljobs7: Adapt Gaby's script (TS_AMM7_Parcels.py) to make it run with Caribbean outputs (test_val.py)

I tried to run some parcels examples, but I keep having an "ImportError: cannot import name 'config'" and also when trying to run Gaby's script (with modifications)

module add anaconda/3-2018_12
conda create -p /work/valegu/pparcels --clone=/packages/lmodmodules/apps/anaconda/3-2018.12
source activate /work/valegu/pparcels
conda install -c conda-forge python=3.6 parcels mpi4py mpich scikit-learn jupyter cartopy ffmpeg

python test_val.py

Traceback (most recent call last):
  File "test_val.py", line 1, in <module>
    from parcels import FieldSet, ParticleSet, ScipyParticle, JITParticle, AdvectionRK4, ParticleFile, Variable
  File "/work/valegu/pparcels/lib/python3.6/site-packages/parcels/__init__.py", line 4, in <module>
    from parcels.fieldset import *  # noqa
  File "/work/valegu/pparcels/lib/python3.6/site-packages/parcels/fieldset.py", line 8, in <module>
    from parcels.field import Field, DeferredArray
  File "/work/valegu/pparcels/lib/python3.6/site-packages/parcels/field.py", line 16, in <module>
    from .fieldfilebuffer import (NetcdfFileBuffer, DeferredNetcdfFileBuffer,
  File "/work/valegu/pparcels/lib/python3.6/site-packages/parcels/fieldfilebuffer.py", line 2, in <module>
    from dask import config as da_conf
ImportError: cannot import name 'config'

**Comment by ocgabs** [comment]
I started testing test_val.py using my old and working parallel PARCELS environment.
On livljobs8
`module load anaconda
source activate /work/gmaya/pparcels`

**Error 1:** OSError: FieldSet files not found: {'lon': ['coordinates.nc'], 'lat': ['coordinates.nc'], 'data': 'Caribbean_RUN1_NEMO4_1m_20100101_20101231_grid_U.nc'}
**Fix:** Full paths to all input files are required (I think).
**Error2:** OSError: FieldSet files not found: {'nav_lon': ['/projectsa/NEMO/gmaya/CollabVG/coordinates.nc'], 'nav_lat': ['/projectsa/NEMO/gmaya/CollabVG/coordinates.nc'], 'data': []}
**Fix:** data file names was wrong Caribbean_RUN1_NEMO4_1m_20100101_20101231_grid_T.nc
actual filenames are: Caribbean_Light_ON_RUN2_1m_20100101_20101231_grid_T.nc
Error3: AssertionError: filename dimension keys must be lon, lat, depth or data

ARNING: Unable to locate chunking hints from dask, thus estimating the max. chunk size heuristically. Please consider defining the 'chunk-size' for 'array' in your local dask configuration file (see https://docs.dask.org).
Exception ignored in: <bound method ParticleFile.__del__ of <parcels.particlefile.ParticleFile object at 0x7fb7641f6048>>
Traceback (most recent call last):
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 195, in __del__
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 200, in close
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 350, in export
RuntimeError: No npy files found in out-CGATHPXF
Exception ignored in: <bound method ParticleFile.__del__ of <parcels.particlefile.ParticleFile object at 0x7fb744712e10>>
Traceback (most recent call last):
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 195, in __del__
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 200, in close
  File "/work/gmaya/pparcels/lib/python3.6/site-packages/parcels/particlefile.py", line 350, in export
RuntimeError: No npy files found in out-FMZKECJD

However OUTPUT.nc gets created

![image](https://user-images.githubusercontent.com/39992236/104074568-5be6cb00-5208-11eb-99b0-4bf69d183ccf.png)
